### ISSUE TITLE
Documentation ? 

### ISSUE THREAD

**Issue by Toshiro-Hitsugaya** [cbovar/ConvNetSharp#53]
What's a volume ? What's a shape ?

**Comment by cbovar** [comment]
A _Volume_ is basically a 4-dimensions matrix (It is often called tensor in other libraries).
A _Volume_ is defined by a type (float/double) and a _Shape_.

The _Shape_ specifies the size of each _Volume's_ dimensions. The last dimension (4th) is the batch size.

### Some examples
a [28x28x3x1] Volume could contain an image (the third dimension is 3 in order to store each RGB channel):
![image](https://user-images.githubusercontent.com/5098385/28248428-3716f330-6a77-11e7-820e-caf995326741.png)


a [1x1x10x1] Volume could be used to store classification result with 10 classes:
![image](https://user-images.githubusercontent.com/5098385/28248467-9eef5268-6a77-11e7-8c50-91153054031d.png)

**Comment by deanhu2** [comment]
Hey after viewing the original project convnetjs I was wondering if the img_to_vol method has been implemented from  the example (var x = `convnetjs.img_to_vol(document.getElementById('some_image')))`   or if there is currently a way to pass in an image and convert it to a volume easily?

**Comment by cbovar** [comment]
@deanhu2 _img_to_vol_ is not implemented in **ConvNetSharp** currently but it would be an useful addition. **ConvNetSharp.Utils** would the correct place to implement such method.
